echo -n "AIzaSyBsdYP2tnsWKK7VN2y2EGCLDocXmfO2ElM" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_API_KEY production
echo -n "stadiumopsai.firebaseapp.com" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production
echo -n "stadiumopsai" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_PROJECT_ID production
echo -n "stadiumopsai.firebasestorage.app" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET production
echo -n "171715681770" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID production
echo -n "1:171715681770:web:65b3e5a24e6581f567e693" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_APP_ID production
echo -n "G-WEYXVP5FFP" | npx vercel@latest env add NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID production
echo -n "production" | npx vercel@latest env add NEXT_PUBLIC_APP_ENV production
echo -n "stadiumopsai" | npx vercel@latest env add FIREBASE_PROJECT_ID production
echo -n "firebase-adminsdk-fbsvc@stadiumopsai.iam.gserviceaccount.com" | npx vercel@latest env add FIREBASE_CLIENT_EMAIL production
echo -n "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhdWu2Y3QfNcey\nnLVMKnWOReaVrPsNlzGldoz5wCqGGZZrwPirKLOSba4iOChmgDbSXtJdBwPM2mCO\nPJi56h0WpsV8ZkJ1hYTYqWryPbJce1TmtF7w5na2pabMn01M9p2vOGgNT7CiZc84\ngKvi0Kou+iHtGyEet3Y1dSBQ67hLrhszXx41AaedO0aDM7/kggovY9vK/6vK9jZe\nk6K2jpBDlXnyABXvAmuxm9f5M9BV5jYgqgKBCnwo2jJSjWRYz9+nPhlDeiuLp/QT\n+nW3XorL4SODS99GN1DHH04yp61gWi9aIeVNFjVjI0AR+4jIVBbMyY81NFqCl63c\nniPvwK8/AgMBAAECggEAAQcH9qIoD/xZbKGfhzlU+nusZqzjIqy4YoinxnuZtgK9\nLMCJtuijPjJBw5DTSPmh8P4oTJmQ6t4T5+deys9w/SlwEku6VyQZ9uLOxKEuBD3g\n+oGCl+vKSWAijSGCDgJnCuVhlANI9XSBUpXuMpprgXX3sZzuCbXMVBy0iP80rSOb\ny0m/80YYDhpbla+37vPcZhTLIIxjECrJd/oz3J/zLLCj6zcbQt4LieWKTWwQCxn4\nmVx7ezZZ+Ce+cXpkmiMyZRbjL9yxRqQmH8up1/KAFfWWq05gTnkVafgJpCSP7Dnc\nMKDFtPFOw8guckElWkW7III92Fy4bNDtNhoyrXf4AQKBgQD3xi0Z2DgEglnD7UPg\nxQEWcifLQ5KCVhhvxq1Hfm+89/HWYPs1kRH9RDCyGWXj9r0+j5OiSHGIGCJVhTbB\nvDBF5+Q1owrU/3CbfcVlHsI+uGilJhRemb4qh6l8zxryN5S/YrZnbqhYXBqMcPuv\nsYO7/A5rbwpcfQaL/EEnn6XSSQKBgQDo8ZYZMwkRyxk01WQyjEBdgMi+PGoQ+0fN\nXeVZ8Egj48xCjCPliD+DDH5n6BAYhEpd2nI5oCtefPbHLuhH3xTbya45RRwTsLWM\nEBqEW76N97/0dFIezZE/D1vdzjuIMqvwHphY+GqvhabKrxAvTVBMUvyM+IlRRrGu\nIye+4mh1RwKBgAtJCnrX301NRptm7iWJs4/7KRbYAA9RrpFAwlm0R5Ca1ngGOMrq\nzZ/0gCdMgtiMP3he/8FvfUROnRm6FJFkaep1Mm7C+1ZSQCXE573AVeaXbaTABEN+\nyyuSvESEBl0r7Ol+rIIvhxlnMIpfBweslSx1wY5hI16tDyRHHAya9+mJAoGAHG54\nMoUvIzPV1MQC4cSKip8QYV/AVmhFIETInIyeUXsZUDoIm5hgoB8jQo1pgYSMCx6B\neJUbFgJMoI0SHsuUoSrhj+3memTEE99XTTZhcLR/gle8OjQ++SJnxQ/J5lrA76Lc\nV2eipd+7NtvdLtjR5y7t0kr3f6sQPr/dtwetVjsCgYEAqzynU9jOIEuvROvr1TZX\n4g2rIzB2HdmuGM/ykHJEWrXUr4YartOnqPfta83+6ZE0MLuHxF6ma8bAiBizPgeb\nqEdDBg/MrnkwkfUn8fIwrslkcHCmIEkzv+//hq2CBgO3XdEGJTiJH8IE14rAnHS2\nCWoi5nq2TsFvdmN+KfMq7v4=\n-----END PRIVATE KEY-----\n" | npx vercel@latest env add FIREBASE_PRIVATE_KEY production
echo -n "AIzaSyD_2yvzaSKMq432O8uZH9K4nBd1_rZ4Cv4" | npx vercel@latest env add GEMINI_API_KEY production
